# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
kotlin.daemon.jvmargs=-Xmx4096m
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true
# Verity
android.injected.testOnly=false
android.enableJetifier=true
android.r8.strictFullModeForKeepRules=false
#android.r8.optimizedResourceShrinking=false

# Project Configuration
project.name=LuckyTool
project.url=https://github.com/luckyzyx/LuckyTool
project.groupName=com.luckyzyx.luckytool
project.stub.groupName=com.luckyzyx.hidden.api.stub
project.android.compileSdk=37
project.android.minSdk=30
project.android.targetSdk=37
project.jdk.version=21
